m4_changequote([,])m4_dnl
m4_define([dnl],m4_defn([m4_dnl]))dnl
m4_define([m4_if],m4_defn([m4_ifelse]))dnl
m4_define([m4_bregexp],m4_defn([m4_regexp]))dnl
m4_define([m4_bpatsubst],m4_defn([m4_patsubst]))dnl
m4_define([AC_DEFUN],m4_defn([m4_define]))dnl
dnl
m4_define([a],[unquoted_a])dnl
m4_define([b],[unquoted_b])dnl
m4_define([c],[unquoted_c])dnl
m4_define([d],[unquoted_d])dnl
dnl
m4_include([jfsugar.m4])dnl
